spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/car_info_clean
    username: car_info_clean
    password: 1234


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    database: h2
server:
  port: 9090

decorator:
  datasource:
    p6spy:
      enable-logging: true

